title: <p align="center"> Deepak Rawat </p>
logo: /assets/img/profile_pic.jpg

description:
  <p align="center">
  <a href="assets/Deepak_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/deepak-rawat-402392229/">LinkedIn</a> |
  <a href="https://github.com/deepak10rawat">GitHub</a>
  
  <br>   
  I am working on machine learning, data science and python. I have worked in many project designs in past using key technologies ranging from embedded to Network centric softwares.
  </p>



theme: jekyll-theme-minimal