title: <p align="center"> Deepak Rawat </p>
logo: /assets/img/profile_pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  
  <br>
  </p>



theme: jekyll-theme-minimal